In [1]:
from sentence_transformers import SentenceTransformer

In [2]:
model = SentenceTransformer('google/embeddinggemma-300m')

Loading weights:   0%|          | 0/314 [00:00<?, ?it/s]

In [5]:
import numpy as np

def cosine_similarity(a, b):
    return np.dot(a, b) / (np.linalg.norm(a) * np.linalg.norm(b))

In [29]:
query = "он сделал доброе дело"
query_embedding = model.encode_query(query)
key_1 = "справедливость восторжествовала"
key_1_embedding = model.encode_document(key_1)
cosine_similarity(query_embedding, key_1_embedding)

np.float32(0.3413521)

In [30]:
key_2 = "зло не спит"
key_2_embedding = model.encode_document(key_2)
cosine_similarity(query_embedding, key_2_embedding)

np.float32(0.27363074)

In [31]:
model.similarity(query_embedding, key_1_embedding)

tensor([[0.3414]])

In [32]:
key_3 = "вчера мы мыли ковер"
key_3_embedding = model.encode_document(key_3)
cosine_similarity(query_embedding, key_3_embedding)

np.float32(0.27804464)

In [15]:
omonim_1 = "Лучник натянул лук перед выстрелом."
omonim_2 = "Лук добавили в овощной салат."
omonim_1_embedding = model.encode_query(omonim_1)
omonim_2_embedding = model.encode_document(omonim_2)
cosine_similarity(omonim_1_embedding, omonim_2_embedding)

np.float32(0.21285632)

In [16]:
omonim_1_embedding = model.encode_query(omonim_1)
omonim_2_embedding = model.encode_query(omonim_2)
cosine_similarity(omonim_1_embedding, omonim_2_embedding)

np.float32(0.31015787)

In [25]:
test_query = "ты модель которая ищет овощи"
test_query_embedding = model.encode_query(test_query)
model.similarity(test_query_embedding, omonim_1_embedding), model.similarity(test_query_embedding, omonim_2_embedding)

(tensor([[0.1614]]), tensor([[0.4319]]))

In [26]:
test2_query = "ты модель которая ищет стрелков"
test2_query_embedding = model.encode_query(test2_query)
model.similarity(test2_query_embedding, omonim_1_embedding), model.similarity(test2_query_embedding, omonim_2_embedding)

(tensor([[0.3568]]), tensor([[0.1294]]))